### ISSUE TITLE
putty.exe does not launch

### ISSUE THREAD

**Issue by gtwy** [lalbornoz/PuTTie#1]
I tried both releases from 2 weeks ago (file and registry), but putty.exe will not open. I disabled the Microsoft Smart Screen filter as a test, but that did not resolve. I tried to run it in a command prompt and it executes, dumps me back at another prompt, and does not provide any type of output about what is going on.

I then went on to try it on my laptop as well, but had the same issue. Both computers are running Windows 10 Pro with latest Windows Updates, have been rebooted, etc. etc.

I am able to run the normal PuTTy program without issue.

**Comment by szepeviktor** [comment]
The same here. Latest zip/putty.exe, no output, no new window, `%errorlevel%` is 0.

**Comment by lalbornoz** [comment]
Apologies, that sounds annoying. This got fixed in 20eacab08468859c30565b7ab5ca2e6f345598a5, could you confirm that putty.exe starts & works now?

**Comment by szepeviktor** [comment]
Thank you.
Now it says "ce33a80b" in the About box.

**Comment by gtwy** [comment]
This appears to be resolved with the latest release. I tested with the "file" version, not the registry version. Thank you for quick response!
