### ISSUE TITLE
Feature request : Increase size with CTRL +/-

### ISSUE THREAD

**Issue by azlux** [lalbornoz/PuTTie#16]
Hi,

I see you already have an option to increase/decrease the font size on CTRL + "Mouse wheel",
Is that possible to have the same behavior with CTRL + "+/-" . I've got the habit with Kitty when I don't have the mouse in hand.

Thank for your work and product,
Have a good day.
Az

**Comment by bastien30** [comment]
Hello,

It would be nice too to be able to revert to default size with "CTRL + 0" :blush:

**Comment by azlux** [comment]
Thanks a lot

**Comment by lars18th** [comment]
Thank you @lalbornoz . But where are the new binary releases to test it? 👼

**Comment by lars18th** [comment]
Hi @lalbornoz ,

I tested this with the last binary release. However, when selecting "Frippery/Mouse/Change fron size with CTRL 0/+/-" the shortcut doesn't work. With the mouse wheel it works, but not with the keyboard. I've checked with NUM-BLOCK and without, and it nevers work. Any idea?

**Comment by lalbornoz** [comment]
It's CTRL + VK_OEM_PLUS/VK_OEM_MINUS, that's the ?/ß/\ and `/' keys on a QWERTY keyboard.

**Comment by lars18th** [comment]
> It's CTRL + VK_OEM_PLUS/VK_OEM_MINUS, that's the ?/ß/\ and `/' keys on a QWERTY keyboard.

Thank you for adding https://github.com/lalbornoz/PuTTie/commit/3ebd6aa36a0290d55ea26be27f971c77383d7d87. What has sense (for me almost) is the use of the keys on the numpad, not on the regular keyboard. However, with small keyboards has sense to support the regular keys as well. Therefore, now it's perfect. 👍 

Thank you!
