### ISSUE TITLE
Feature Request / Discussion: -launcher option?

### ISSUE THREAD

**Issue by dsl101** [lalbornoz/PuTTie#18]
Another KiTTy immigrant here, and missing a couple of things... I saw in another issue the thought about discussing features rather than just asking for everything from KiTTy to be implemented, which I'm totally comfortable with. But I'm really missing the `-launcher` option from KiTTy, as I have dozens of sessions saved and that provided such easy access to them, plus to current sessions, the config window, etc.

Would that be better as a separate executable? How would it work with the various versions of PuTTie (I'm using Portable atm)? Could it easily be built into the main executables? Or are there other, better ways to make that 'shortcut menu'?

**Comment by lars18th** [comment]
Hi @dsl101 ,

The `-launcher` functionality of KiTTY is described here: https://www.9bis.net/kitty/index.html#!pages/SessionLauncher.md

I feel this could be a powerful functionality. However, it could be hard to implement it. And futhermore, the FOLDER support could be preferable before implementing this, because without folders the list of saved sessions could be huge. Don't you think so?

**Comment by lars18th** [comment]
> Yes, I agree about folder support—I use it extensively in KiTTy. I'm using KiTTy portable, and the session files are organised in folders on disk as well as in the UI.

Me too. However, we have to wait until this (or other) requests can be implemented in PuTTie. I don't want to ask @lalbornoz for a bunch of features for the sole reason that they exist in KiTTY. Note that PuTTie is not KiTTY. It's a new fork, very well organised and designed. So, I suggest first to discuss about any new functionality request. Anyway, IMHO the folder support is a must-have, but I prefer to go slowly. Do you agree?

**Comment by dsl101** [comment]
Well, I guess with all these kinds of projects, it goes at the speed it can given the people who can work on / contribute. I'm afraid this is out of my area of expertise to directly contribute to, but I'd be keen to see both a launcher and folders, and it does make sense that folders would come first.

**Comment by lars18th** [comment]
Hi @dsl101 ,

> it does make sense that folders would come first.

FYI I've requested this in #28 .
