### ISSUE TITLE
Feature request - persistent keys in pageant

### ISSUE THREAD

**Issue by gtwy** [lalbornoz/PuTTie#2]
Prior to PuTTie, I was using [PuTTy-Tray](https://puttytray.goeswhere.com/), a dead PuTTy fork. One of the best features was its ability to persist keys in pageant so that I did not have to constantly browse to the key files every time I restarted my PC. Further, their pageant.exe had an option to "start with windows."

I have solved the "start with windows" feature by adding a shortcut to pageant.exe in shell:startup, but I do not have a work around to make keys persist in the program itself. I have to manually browse to each key and select it. Is this something that can be added?

I very much appreciate it!!

**Comment by lalbornoz** [comment]
Well, I could implement that - assuming that by persisting keys you mean persisting the filenames/pathnames not the passphrases - but PuTTy/ie's Pageant already kinda supports that, or at least wrt. the having to constantly browse to the key files part. You can just pass the filenames to Pageant as arguments and it'll load them on startup, which is what I personally do. 
Would that work for you?

**Comment by gtwy** [comment]
Definitely just the path names, not the passphrases!

I did not realize I could pass the filenames to pageant to load them. I can probably figure that out and implement on my side, but could be a nice feature for others if you ever want to implement it in the GUI. On PuTTy-Tray, the options to "Persist Keys" and "Launch at Startup" were checkbox items when you would right click on the Pageant icon.

**Comment by lalbornoz** [comment]
I've implemented both features, they're available in https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-0af03d91 and https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-file-Release-0af03d91.

Could you please confirm that this works for you as it ought?

**Comment by gtwy** [comment]
Works great. Keys persist after reboot, program starts with windows and it asks me to type the key in when it launches. Thanks so much!
