### ISSUE TITLE
Portable Version - can't save sessions

### ISSUE THREAD

**Issue by wiesl** [lalbornoz/PuTTie#20]
Hello,

Using version: bd659898, putty-portable.exe on another drive than C: (e.g. Y:)

Then sessions can't be saved as temp files are created on C: and can't be moved to Y:

Error happens in function WfrSaveTreeToFile in line 528:
	if (WFR_SUCCESS(status)
	&&  WFR_FAILURE_WINDOWS(status, MoveFileExW(
			fname_tmpW, fname_fullW, MOVEFILE_REPLACE_EXISTING)))

Why do you use a temp file and move it then and not just directly writing it to the path? That avoids the problem.

Thnx.

**Comment by lalbornoz** [comment]
> Then sessions can't be saved as temp files are created on C: and can't be moved to Y:
Why can't they be moved to Y:? I've just tested this (putty-portable.exe on Y:, save session) and it works for me.

**Comment by lars18th** [comment]
Hi @wiesl ,

It's your C: drive readonly?

**Comment by wiesl** [comment]
Nothing is readonly, neither C: nor Y:
Y: is a writeable Veracrypt Drive.

**Comment by lalbornoz** [comment]
What's the specific error you're getting?

**Comment by wiesl** [comment]
Can not move the file to a different drive.

**Comment by lalbornoz** [comment]
Is that the error you're getting from PuTTie? Because you should be getting one. Either way, this isn't helping.

**Comment by lalbornoz** [comment]
ERROR_NOT_SAME_DEVICE?

**Comment by wiesl** [comment]
Thnx, but doesn't work. Same error message.
Why do you save it in temp directory anyway and not directly on final destination?

**Comment by lalbornoz** [comment]
> Thnx, but doesn't work. Same error message.
Which release?

> Why do you save it in temp directory anyway and not directly on final destination?
Because in error paths saving files in-place would mess up th file that's currently there, which would necessitate backing it up first and then, on error, restoring it. Either way, that isn't the source of the error one way or another.

**Comment by wiesl** [comment]
Tested release: bd659898

**Comment by lalbornoz** [comment]
Can't reproduce this w/ https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-0c75a77a on Windows 10 with identical setup (minus using a virtual disk as Y:), confirmed w/ Process Monitor that a temporary file gets created and written to on C: first and then copied to Y:. Sorry, can't help you.

**Comment by lalbornoz** [comment]
[putty-portable.zip](https://github.com/lalbornoz/PuTTie/files/15368755/putty-portable.zip)
Does this work for you?
