### ISSUE TITLE
Change application signature - for pin to taskbar grouping

### ISSUE THREAD

**Issue by kiloforce** [lalbornoz/PuTTie#23]
When I try to pin PuTTie to the taskbar, it thinks it is PuTTY.  So when I try to click on the pinned application to open it up, it opens up PuTTY instead.  I tried renaming the executable, but this did not fix it.  It must be using the signature, or embedded property, of the application, to determine "grouping" on the taskbar?

**Comment by lars18th** [comment]
HI,

I support this request. KiTTie is not PuTTY, so it makes sense for them to be considered as different programs. Also, I suggest changing the ICON for it. For example, you can reuse the KiTTY icons.

**Comment by lalbornoz** [comment]
Can you confirm 9528a46 fixes this in the latest release (https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-ae93ad9d)?

**Comment by lalbornoz** [comment]
Guess that's a yes.

**Comment by kiloforce** [comment]
Can confirm that this fixed the "pin" issue.  Curious why not also rename the binary to puttie.exe?

**Comment by lalbornoz** [comment]
tru

**Comment by lars18th** [comment]
Hi @lalbornoz ,

Thank you for the custom icons. However, any idea why not all binaries are using the new icons?

![PuTTie icons](https://github.com/lalbornoz/PuTTie/assets/9989964/1f31797c-e5e0-4350-9393-23ff35af8492)

**Comment by lalbornoz** [comment]
The files are identical so they all contain the same icons. Icon cache, maybe?

**Comment by lars18th** [comment]
> The files are identical so they all contain the same icons. Icon cache, maybe?

I'll do more tests in other computers. Thanks for your great work with this powerful PuTTY fork!

**Comment by lalbornoz** [comment]
Thanks!
