### ISSUE TITLE
BUG: Resizable configuration window

### ISSUE THREAD

**Issue by lars18th** [lalbornoz/PuTTie#24]
Hi @lalbornoz ,

Thank you for implementing the request for enhance the size of the Configuration Window (#15). However, the current implementation have some bugs:

1. The default rendering is ugly. See this screenshot of the default size:
![PuTTie](https://github.com/lalbornoz/PuTTie/assets/9989964/5fea5bec-8f1c-4b49-8ddb-c71017437f4a)

The [About], [Help], [Open] and [Cancel] buttons are not accessible. You can show them only when passing the mouse over them, because they are overprinted by the Category and Saved Sessions objects. And the section "Close window on exit" is completely hidden.

2. If you resize the Window to the minimum, a bug appears: the program enters in a infinite loop and you need to kill it. And when you restart it, the problem continues as you can't change the size. The only solution is to edit manually the `PuttyConfigLastSize` value.

Therefore, I suggest this:
- Define a fixed value for MIN_CONF_H_SIZE and MIN_CONF_V_SIZE.
- When resizing the Config Window, every time check the minimum boundary, to not reduce more than these values.
- When starting, check if the `PuttyConfigLastSize` is respecting the boundary; and restatore the minimum value if it's needed.
- In addition, get the total screen size (desktop size, not the monitor size with a multi-monitor setup), and if the size is over the desktop size then don't go over this size. This is necessary when opening in a computer with a desktop smaller than the stored value.
- Finally, try to render the Config Window with resizing, but respecting the bottom part of the window.

I hope you want to fix this. And thank you for your effort.

Note: Perhaps it has sense to also include a config value like `PuttyConfigFixSize` (default off) to disable the resize. Then the user could set a fixed value with `PuttyConfigLastSize` disabling the UI changes. What you think?

**Comment by lalbornoz** [comment]
Oh jesus christ, fuck that then. Going to disable that code, PuTTY is too much of a piece of shit for this to be worth bothering with.

**Comment by lalbornoz** [comment]
What's your system font and font size?

**Comment by lalbornoz** [comment]
Right, nevermind. This is broken upstream, all positions and sizes are hard-coded, because upstream feels like this is 1995 and we're all using 640x480 PCs. Doing this right would entail reimplementing the godawful upstream UI "£%&*("£&*)(%£& code, which I'm not prepared to do. Guess it's back to the original tiny configuration window because that's how Simon Tatham seems to think the world gotta work for all of us smfh.

**Comment by lars18th** [comment]
You're right. And the only _simple_ solution is to increase the number of saved sessions. Therefore, the last implementation is the maximum that you can do.

Regards.
