### ISSUE TITLE
Force file storage without renaming executable

### ISSUE THREAD

**Issue by bastien30** [lalbornoz/PuTTie#25]
Is there a possibility of specifying file storage without having to rename all executable and without appending "--file" parameter ?

I use file storage but it seems there is almost only registry versions released on Github.

Using renamed versions seems to break interaction between differents components.
For example, if I rename pageant.exe to pageant-file.exe, it still search for putty.exe and not puttie-file.exe (by the way, I think the fact that it calls putty.exe is a bug following the renaming of putty.exe to puttie.exe), so the quick session launch doesn't works.

I understand the convenience of renaming executables to choose storage type, but I don't find it practical to use, at least in my use-case.

Is there a possibility forcing storage type no matter what executable is used ?
Or can you provides file version of latest releases ?

Thanks.

**Comment by lalbornoz** [comment]
Agree actually, I'll be providing both releases again from now on. The *-<backend>.exe mechanism is useful but not for this purpose. And yes, it should be calling "puttie.exe", that's a bug, thanks for the report.

wrt. pageant-file.exe calling puttie-file.exe: it doesn't have to, it just passes whatever backend was selected along via --file/--registry/--ephemeral (or at least it should.)

**Comment by bastien30** [comment]
Thank you so much :pray:
