### ISSUE TITLE
About Window: incorrent rendering? 

### ISSUE THREAD

**Issue by lars18th** [lalbornoz/PuTTie#27]
Hi @lalbornoz ,

It's an aesthetic issue. But I prefer if you fix it (the text is not centred, neither horizontally nor vertically):
![About PuTTie](https://github.com/lalbornoz/PuTTie/assets/9989964/9324c4b6-a2c1-4b25-863b-5d9acb7d7aab)

**Comment by lars18th** [comment]
Hi,

And please add the PuTTY version on which PuTTie is based. For example:
```
[...]

             PuTTie Release build ########
                  PuTTY Release 0.81

[...]

    Source commit: Git commit 77886b84 on branch master

             (c) (of fork) [...] lalbornoz
```

**Comment by lalbornoz** [comment]
> Hi,
> 
> And please add the PuTTY version on which PuTTie is based. For example:
> 
> ```
> [...]
> 
>              PuTTie Release build #######
>              Based on  PuTTY Release 0.81
> 
> [...]
> 
>     Source commit: Git commit 77886b84 on branch master
> 
>              (c) (of fork) [...] lalbornoz
> ```

It's already in there, you weren't able to see it because the richedit control was too small to show all the text.

**Comment by lars18th** [comment]
Hi @lalbornoz ,

Thank you, now fixed. 👍 
```
PuTTie 💚

PuTTie Release build (Git commit 9c97eba9 on branch master) 

Build platform: 64-bit x86 Windows
Compiler: gcc 12-win32
Embedded HTML Help file: no
Source commit: 9c97eba92d474d5c3ba9e68c9856ac80d28d2107 

© 1997-2024 Simon Tatham. All rights reserved. 
© 2018, 2022, 2023 Lucía Andrea Illanes Albornoz. All rights reserved.
```

But, I recommend that you change this line:
```
PuTTie Release build (Git commit 9c97eba9 on branch master) 
```
with this:
```
PuTTie Release build (Based on PuTTY 0.81) 
```
Take note that `commit 9c97eba9` is the value `Source commit:`. And because you're getting _manually_ the source code of the PuTTY, then you can update _manually_ the version number. Is not a huge effort, and it will be useful for a fast check of the version of PuTTie _and_ the core of PuTTY. 😉
