### ISSUE TITLE
Windows Installer [Feature Request]

### ISSUE THREAD

**Issue by kiloforce** [lalbornoz/PuTTie#29]
Would be nice to have a Windows Installer.  Maybe a simple MSI installer created using WiX?

**Comment by lars18th** [comment]
Hi,

If you _really_ need this, the source file from the original PuTTY is already here: https://github.com/lalbornoz/PuTTie/blob/master/windows/installer.wxs

**Comment by lalbornoz** [comment]
As was said, if you really need this, upstream PuTTY has a WiX installer file for this, though it'd need some minimal changes.
