### ISSUE TITLE
Keys are not caching correctly in file version of PuTTie (%appdata%\PuTTie\hostkeys)

### ISSUE THREAD

**Issue by gtwy** [lalbornoz/PuTTie#3]
This prompts every time I log into a server. I am using the "file" release.
![image](https://user-images.githubusercontent.com/11441407/217059085-75261141-3ff3-48c8-a57b-010b1df7911b.png)

When I click Accept, I assume it will cache the key, but it does not.

Sessions are saving correctly
![image](https://user-images.githubusercontent.com/11441407/217058677-a9ea9e45-a2b5-4bb0-bb3f-83d7ac803d78.png)

Host keys are not
![image](https://user-images.githubusercontent.com/11441407/217058781-5e9a560f-8af6-4a9c-b28a-03e90de44087.png)

Digging through the program further, it appears that the host keys are being saved in the registry despite all of my settings set to "file." Note that I have not yet changed any settings in PuTTie, I am using it totally stock.

![image](https://user-images.githubusercontent.com/11441407/217059622-5f496c03-450f-4654-b825-b02bd7675d24.png)
![image](https://user-images.githubusercontent.com/11441407/217059737-88a90ec8-9937-4c42-848d-cf4edd7f9631.png)

I feel bad for opening so many tickets. Is there a donation button somewhere? I couldn't find one on the main page.

**Comment by lalbornoz** [comment]
Oh hey thanks for reporting that! Didn't realise mentioning the issue in a Git commit would automatically close it. Anyway, this should be fixed in the upcoming releases I'm about to publish (waiting for builds to finish.)

**Comment by lalbornoz** [comment]
https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-registry-Release-01cae3ea
https://github.com/lalbornoz/PuTTie/releases/tag/PuTTie-file-Release-01cae3ea

Does that fix it for you?

**Comment by gtwy** [comment]
Sorry for the delay. That did fix this issue. I verified that the host key did show up in the correct folder.

**Comment by lalbornoz** [comment]
Awfom!
