### ISSUE TITLE
URLs regex setting getting truncated.

### ISSUE THREAD

**Issue by SamKook** [lalbornoz/PuTTie#6]
If I go to the URLs setting page and then back to the sessions to save my settings, then the regex for the URLs gets truncated to 63 characters long and launching that session will give the error "Error compiling clickable URL regex" and the only way to save it back to something valid is to edit the registry.

The default "((https?|ftp)://|www\.).(([^ ]*\([^ ]*\))([^ ()]*[^ ,;.:"')>])?|([^ ()]*[^ ,;.:"')>]))" becomes "((https?|ftp)://|www\.).(([^ ]*\([^ ]*\))([^ ()]*[^ ,;.:"')>])?".

I just installed PuTTie-registry-Release-1bfd0b26 for the first time(was using puttytray before) and tested it on my windows 10 system as well as a clean windows 11 VM with the same result.

**Comment by SamKook** [comment]
Messed around a bit with the URL regex with PuTTie-registry-Release-a0cf0752 and haven't had any issues so seems fixed.

**Comment by lalbornoz** [comment]
Glad to hear that! Thanks for the bug report!
