### ISSUE TITLE
Error when restarting session after timeout at login

### ISSUE THREAD

**Issue by SamKook** [lalbornoz/PuTTie#7]
If I open a session and let it timeout at the login(username or password prompt), right-click the top left icon to bring up the menu and select Restart Session, an Assertion failed! error pops up.
![Assertion_failed_puttie](https://user-images.githubusercontent.com/84121956/234395368-4e0492ce-22c8-4bb9-bd81-31e2d9107eb2.png)

Abort or Retry will close PuTTie but Ignore lets you try to login again as expected.

Tested with PuTTie-registry-Release-a0cf0752

**Comment by lalbornoz** [comment]
Thanks for the bug report! This should be fixed in the upcoming releases.
